apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-controller-pre
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: module-controller
  template:
    metadata:
      labels:
        app: module-controller
    spec:
      serviceAccountName: virtual-kubelet
      containers:
        - name: module-controller
          image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/release/module-controller-v2:v2.1.2
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1000m"
              memory: "400Mi"
          env:
            - name: ENABLE_MODULE_DEPLOYMENT_CONTROLLER
              value: "true"
            - name: ENABLE_MQTT_TUNNEL # mqtt tunnel flag
              value: "true" # true means enable, if enable mqtt tunnel, please configure env below
            - name: MQTT_BROKER # mqtt broker url
              value: YOUR_MQTT_BROKER_ENDPOINT
            - name: MQTT_PORT # mqtt port
              value: YOUR_MQTT_PORT
            - name: MQTT_USERNAME # mqtt username
              value: YOUR_MQTT_USERNAME
            - name: MQTT_PASSWORD # mqtt password
              value: YOUR_MQTT_PASSWORD
            - name: MQTT_CLIENT_PREFIX # mqtt client prefix
              value: YOUR_MQTT_CLIENT_PREFIX
            - name: ENABLE_HTTP_TUNNEL # http tunnel flag
              value: "true" # true means enable, if enable mqtt tunnel, you can choose to configure env below
            - name: HTTP_TUNNEL_LISTEN_PORT # Module Controller HTTP Tunnel listen port, use 7777 for default
              value: "7777"
            - name: REPORT_HOOKS # error report hooks, only support dingTalk robot webhook
              value: YOUR_REPORT_HOOKS
            - name: ENV # module controller env, will set to vnode labels
              value: YOUR_ENV
            - name: IS_CLUSTER # cluster flag, if true, will use cluster configure to start virtual kubelet
              value: "false"
            - name: WORKLOAD_MAX_LEVEL # cluster configure, means max workload level for workload calculation in virtual kubelet, default is 3
              value: "3"
            - name: ENABLE_MODULE_DEPLOYMENT_CONTROLLER # module deployment controller flag, if true, will start deployment controller to modify module deployment's replicas and baseline
              value: "true"
            - name: VNODE_WORKER_NUM # VNode concurrent module processing thread number, set to 1 to indicate single thread
              value: "8"