apiVersion: apps/v1
kind: Deployment
metadata:
  name: biz1-web-single-host
  labels:
    virtual-kubelet.koupleless.io/component: module-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      virtual-kubelet.koupleless.io/component: module
      module.koupleless.io/name: biz1-web-single-host
      module.koupleless.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        virtual-kubelet.koupleless.io/component: module
        module.koupleless.io/name: biz1-web-single-host
        module.koupleless.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - name: biz1-web-single-host  # this name must same with the biz name defined in the jar
          image: https://koupleless-dosc.oss-cn-hongkong.aliyuncs.com/biz1-web-single-host-0.0.1-SNAPSHOT-ark-biz.jar
          env:
            - name: BIZ_VERSION
              value: 0.0.1-SNAPSHOT
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # these labels in vnode generated in base `https://github.com/koupleless/runtime/blob/main/arklet-core/src/main/java/com/alipay/sofa/koupleless/arklet/core/hook/base/BaseMetadataHookImpl.java`
                  # you can define your own labels by implementing your own BaseMetadataHookImpl
                  - key: base.koupleless.io/name
                    operator: In
                    values:
                      - TO_BE_IMPLEMENTED
                  - key: base.koupleless.io/cluster-name
                    operator: In
                    values:
                      - default
        podAntiAffinity: # 打散调度核心配置
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                  virtual-kubelet.koupleless.io/component: module
                  module.koupleless.io/name: biz1-web-single-host
                  module.koupleless.io/version: 0.0.1-SNAPSHOT
            topologyKey: topology.kubernetes.io/zone
      tolerations:
        - key: "schedule.koupleless.io/virtual-node"
          operator: "Equal"
          value: "True"
          effect: "NoExecute"
        - key: "schedule.koupleless.io/node-env"
          operator: "Equal"
          value: "dev"
          effect: "NoExecute"
